SELECT * FROM SZPITALE;
SELECT * FROM ODDZIALY;
SELECT * FROM SALE_ZABIEGOWE;
SELECT * FROM ZABIEGI;

DELETE SZPITALE
	WHERE nazwa='Mazowiecki Szpital Brodnowski';

SELECT * FROM SZPITALE;
SELECT * FROM ODDZIALY;
SELECT * FROM SALE_ZABIEGOWE;
SELECT * FROM ZABIEGI