Use BSK_2
go

DROP TABLE RECEPTY;
DROP TABLE TRANSPORTY;
DROP TABLE BTPOBYT_LEKARZE;
DROP TABLE LEKARZE;
DROP TABLE POBYT;
DROP TABLE PACJENCI;
DROP TABLE ZABIEGI;
DROP TABLE CHOROBY;
DROP TABLE KARETKI;
DROP TABLE SALE_ZABIEGOWE;
DROP TABLE ODDZIALY;
DROP TABLE SZPITALE;

