Use BSK_2
go

Drop Security Policy MacSec.SensitiveData
Drop Security Policy MacSec.SensitiveData1
Drop Security Policy MacSec.SensitiveData2
Drop Function MacSec.fn_SecretClearance

DROP TABLE RECEPTY;
DROP TABLE TRANSPORTY;
DROP TABLE BTPOBYT_LEKARZE;
DROP TABLE LEKARZE;
DROP TABLE POBYT;
DROP TABLE PACJENCI;
DROP TABLE ZABIEGI;
DROP TABLE CHOROBY;
DROP TABLE KARETKI;
DROP TABLE SALE_ZABIEGOWE;
DROP TABLE ODDZIALY;
DROP TABLE SZPITALE;
DROP TABLE MacSec.Users;

